### ISSUE TITLE
没有找到sourcemap-rewind模块

### ISSUE THREAD

**Issue by xuxiaoyang883** [ClassicOldSong/sourcemap-rewind#6]
在我自己的项目里 终端运行 npm i sourcemap-rewind -D  新建一个js文件，
·const rewind = require('sourcemap-rewind');
rewind('./dist/js/*.js','Output/directory/path');·
运行该js文件显示sourcemap-rewind模块没有找到

**Comment by ClassicOldSong** [comment]
This project is no longer maintained. Use command line interface or re-check your installation.
